ICT283 Assignment 1: DateTest.cpp File Reference
DateTest.cpp File Reference
#include <iostream>
#include "Date.h"
Functions
string Test1CheckDefaultConstructor ()
string Test2CheckParameterizedConstructor ()
string Test3CheckDayOfMonthGetter ()
string Test4CheckMonthGetter ()
string Test5CheckYearGetter ()
string Test6CheckDayOfMonthSetter ()
string Test7CheckMonthSetter ()
string Test8CheckYearSetter ()
int main ()
Function Documentation
main()
int main ()
Definition at line 15 of file DateTest.cpp.
 {
     cout << "DATE CLASS TEST\n" << endl;
     cout << Test1CheckDefaultConstructor() << endl;
     cout << Test2CheckParameterizedConstructor() << endl;
     cout << Test3CheckDayOfMonthGetter() << endl;
     cout << Test4CheckMonthGetter() << endl;
     cout << Test5CheckYearGetter() << endl;
     cout << Test6CheckDayOfMonthSetter() << endl;
     cout << Test7CheckMonthSetter() << endl;
     cout << Test8CheckYearSetter() << endl;
     return 0;
 }
Test1CheckDefaultConstructor()
string Test1CheckDefaultConstructor ()
Definition at line 32 of file DateTest.cpp.
 {
     cout << "Test 1 - Default constructor correctly initializes data: ";
     Date anniversary;
     if ((anniversary.GetDayOfMonth() == 0)
         && (anniversary.GetMonth() == 0)
         && (anniversary.GetYear() == 0))
     {
         return "PASS";
     }
     else
     {
         return "FAIL";
     }
 }
References Date::GetDayOfMonth(), Date::GetMonth(), and Date::GetYear().
Test2CheckParameterizedConstructor()
string Test2CheckParameterizedConstructor ()
Definition at line 48 of file DateTest.cpp.
 {
     cout << "Test 2 - Parameterized constructor correctly initializes data: ";
     Date birthdate(5,11,2000);
     if ((birthdate.GetDayOfMonth() == 5)
         && (birthdate.GetMonth() == 11)
         && (birthdate.GetYear() == 2000))
     {
         return "PASS";
     }
     else
     {
         return "FAIL";
     }
 }
References Date::Date(), Date::GetDayOfMonth(), Date::GetMonth(), and Date::GetYear().
Test3CheckDayOfMonthGetter()
string Test3CheckDayOfMonthGetter ()
Definition at line 64 of file DateTest.cpp.
 {
     cout << "Test 3 - Day of month getter returns correct value: ";
     Date birthdate(5,11,2000);
     if (birthdate.GetDayOfMonth() == 5)
     {
         return "PASS";
     }
     else
     {
         return "FAIL";
     }
 }
References Date::Date(), and Date::GetDayOfMonth().
Test4CheckMonthGetter()
string Test4CheckMonthGetter ()
Definition at line 78 of file DateTest.cpp.
 {
     cout << "Test 4 - Month getter returns correct value: ";
     Date birthdate(5,11,2000);
     if (birthdate.GetMonth() == 11)
     {
         return "PASS";
     }
     else
     {
         return "FAIL";
     }
 }
References Date::Date(), and Date::GetMonth().
Test5CheckYearGetter()
string Test5CheckYearGetter ()
Definition at line 92 of file DateTest.cpp.
 {
     cout << "Test 5 - Year getter returns correct value: ";
     Date birthdate(5,11,2000);
     if (birthdate.GetYear() == 2000)
     {
         return "PASS";
     }
     else
     {
         return "FAIL";
     }
 }
References Date::Date(), and Date::GetYear().
Test6CheckDayOfMonthSetter()
string Test6CheckDayOfMonthSetter ()
Definition at line 106 of file DateTest.cpp.
 {
     cout << "Test 6 - Day of month setter sets correct value: ";
     Date anniversary;
     anniversary.SetDayOfMonth(2);
     if (anniversary.GetDayOfMonth() == 2)
     {
         return "PASS";
     }
     else
     {
         return "FAIL";
     }
 }
References Date::GetDayOfMonth(), and Date::SetDayOfMonth().
Test7CheckMonthSetter()
string Test7CheckMonthSetter ()
Definition at line 121 of file DateTest.cpp.
 {
     cout << "Test 7 - Month setter sets correct value: ";
     Date anniversary;
     anniversary.SetMonth(10);
     if (anniversary.GetMonth() == 10)
     {
         return "PASS";
     }
     else
     {
         return "FAIL";
     }
 }
References Date::GetMonth(), and Date::SetMonth().
Test8CheckYearSetter()
string Test8CheckYearSetter ()
Definition at line 136 of file DateTest.cpp.
 {
     cout << "Test 8 - Year setter sets correct value: ";
     Date anniversary;
     anniversary.SetYear(2021);
     if (anniversary.GetYear() == 2021)
     {
         return "PASS";
     }
     else
     {
         return "FAIL";
     }
 }
References Date::GetYear(), and Date::SetYear().