ICT283 Assignment 1: SensorRecordTest.cpp File Reference
SensorRecordTest.cpp File Reference
#include <iostream>
#include "SensorRecord.h"
Functions
string Test1CheckDefaultConstructor ()
string Test2CheckSetters ()
int main ()
Function Documentation
main()
int main ()
Definition at line 8 of file SensorRecordTest.cpp.
 {
     cout << "SENSOR RECORD CLASS TEST\n" << endl;
     cout << Test1CheckDefaultConstructor() << endl;
     cout << Test2CheckSetters() << endl;
     return 0;
 }
Test1CheckDefaultConstructor()
string Test1CheckDefaultConstructor ()
Definition at line 17 of file SensorRecordTest.cpp.
 {
     cout << "Test 1 - Default constructor correctly initializes data: ";
     SensorRecord sensorRec;
     if ((sensorRec.GetWindSpeed() == 0) && (sensorRec.GetAirTemperature() == 0)
             && (sensorRec.GetSolarRadiation() == 0))
     {
         return "PASS";
     }
     else
     {
         return "FAIL";
     }
 }
References SensorRecord::GetAirTemperature(), SensorRecord::GetSolarRadiation(), and SensorRecord::GetWindSpeed().
Test2CheckSetters()
string Test2CheckSetters ()
Definition at line 32 of file SensorRecordTest.cpp.
 {
     cout << "Test 2 - Setters set correct values: ";
     SensorRecord sensorRec;
     Date newDate(12, 2, 2023);
     Time newTime("8", "0");
     sensorRec.SetDate(newDate);
     sensorRec.SetTime(newTime);
     sensorRec.SetAirTemperature(22.5);
     if (sensorRec.GetDate().GetMonth() == 2 && sensorRec.GetAirTemperature() == 22.5)
     {
         return "PASS";
     }
     else
     {
         return "FAIL";
     }
 }
References Date::Date(), SensorRecord::GetAirTemperature(), SensorRecord::GetDate(), Date::GetMonth(), SensorRecord::SetAirTemperature(), and SensorRecord::SetDate().