ICT283 Assignment 1: SensorRecord Class Reference
SensorRecord Class Reference
Represents a sensor record with date, time, wind speed, air temperature, and solar radiation.
#include <SensorRecord.h>
Public Member Functions
SensorRecord ()
Default constructor for SensorRecord class.
SensorRecord (const Date &date, const Time &time, const float windSpeed, const float airTemperature, const float solarRadiation)
Parameterized constructor for SensorRecord class.
const Date GetDate () const
Retrieve the date of the sensor record.
const Time GetTime () const
Retrieve the time of the sensor record.
const float GetWindSpeed () const
Retrieve the wind speed in the sensor record.
const float GetAirTemperature () const
Retrieve the air temperature in the sensor record.
const float GetSolarRadiation () const
Retrieve the solar radiation in the sensor record.
void SetDate (const Date &date)
Set the date of the sensor record.
void SetTime (const Time &time)
Set the time of the sensor record.
void SetWindSpeed (float windSpeed)
Set the wind speed in the sensor record.
void SetAirTemperature (float airTemp)
Set the air temperature in the sensor record.
void SetSolarRadiation (float solarRadiation)
Set the solar radiation in the sensor record.
Private Attributes
Date m_date
Time m_time
float m_windSpeed
float m_airTemperature
float m_solarRadiation
Detailed Description
Represents a sensor record with date, time, wind speed, air temperature, and solar radiation.
The class provides methods to get and set the individual components of a sensor record.
Author
Josie Lim
Version
1.0
Date
29/02/2024
Definition at line 23 of file SensorRecord.h.
Constructor & Destructor Documentation
SensorRecord() [1/2]
SensorRecord::SensorRecord ()
Default constructor for SensorRecord class.
Definition at line 3 of file SensorRecord.cpp.
     : m_windSpeed(0), m_airTemperature(0), m_solarRadiation(0)
 {
 }
References m_airTemperature, m_solarRadiation, and m_windSpeed.
SensorRecord() [2/2]
SensorRecord::SensorRecord (const Date & date, const Time & time, const float windSpeed, const float airTemperature, const float solarRadiation)
Parameterized constructor for SensorRecord class.
Parameters
date The date of the sensor record.
time The time of the sensor record.
windSpeed Wind speed in the sensor record.
airTemperature Air temperature in the sensor record.
solarRadiation Solar radiation in the sensor record.
Definition at line 9 of file SensorRecord.cpp.
     : m_date(date), m_time(time), m_airTemperature(airTemperature)
 {
     m_windSpeed = windSpeed * 3.6;
     m_solarRadiation = solarRadiation / 6000;
 }
References m_airTemperature, m_date, m_solarRadiation, m_windSpeed, and SensorRecord().
Referenced by SensorRecord().
Member Function Documentation
GetAirTemperature()
const float SensorRecord::GetAirTemperature () const
Retrieve the air temperature in the sensor record.
Returns
The air temperature.
Definition at line 32 of file SensorRecord.cpp.
 {
     return m_airTemperature;
 }
References m_airTemperature.
Referenced by Test1CheckDefaultConstructor(), and Test2CheckSetters().
GetDate()
const Date SensorRecord::GetDate () const
Retrieve the date of the sensor record.
Returns
The date.
Definition at line 17 of file SensorRecord.cpp.
 {
     return m_date;
 }
References m_date.
Referenced by Test2CheckSetters().
GetSolarRadiation()
const float SensorRecord::GetSolarRadiation () const
Retrieve the solar radiation in the sensor record.
Returns
The solar radiation.
Definition at line 36 of file SensorRecord.cpp.
 {
     return m_solarRadiation;
 }
References m_solarRadiation.
Referenced by Test1CheckDefaultConstructor().
GetTime()
const Time SensorRecord::GetTime () const
Retrieve the time of the sensor record.
Returns
The time.
Definition at line 22 of file SensorRecord.cpp.
 {
     return m_time;
 }
GetWindSpeed()
const float SensorRecord::GetWindSpeed () const
Retrieve the wind speed in the sensor record.
Returns
The wind speed.
Definition at line 27 of file SensorRecord.cpp.
 {
     return m_windSpeed;
 }
References m_windSpeed.
Referenced by Test1CheckDefaultConstructor().
SetAirTemperature()
void SensorRecord::SetAirTemperature (float airTemp)
Set the air temperature in the sensor record.
Parameters
airTemp The air temperature to be set.
Definition at line 57 of file SensorRecord.cpp.
 {
     m_airTemperature = airTemp;
 }
References m_airTemperature.
Referenced by Test2CheckSetters().
SetDate()
void SensorRecord::SetDate (const Date & date)
Set the date of the sensor record.
Parameters
date The date to be set.
Definition at line 41 of file SensorRecord.cpp.
 {
     m_date = date;
 }
References m_date.
Referenced by Test2CheckSetters().
SetSolarRadiation()
void SensorRecord::SetSolarRadiation (float solarRadiation)
Set the solar radiation in the sensor record.
Parameters
solarRadiation The solar radiation to be set.
Definition at line 62 of file SensorRecord.cpp.
 {
     m_solarRadiation = solarRadiation / 6000;
 }
References m_solarRadiation.
SetTime()
void SensorRecord::SetTime (const Time & time)
Set the time of the sensor record.
Parameters
time The time to be set.
Definition at line 46 of file SensorRecord.cpp.
 {
     m_time = time;
 }
SetWindSpeed()
void SensorRecord::SetWindSpeed (float windSpeed)
Set the wind speed in the sensor record.
Parameters
windSpeed The wind speed to be set.
Definition at line 51 of file SensorRecord.cpp.
 {
     m_windSpeed = windSpeed * 3.6;
 }
References m_windSpeed.
Member Data Documentation
m_airTemperature
float SensorRecord::m_airTemperature private
Definition at line 29 of file SensorRecord.h.
Referenced by GetAirTemperature(), SensorRecord(), and SetAirTemperature().
m_date
Date SensorRecord::m_date private
Definition at line 26 of file SensorRecord.h.
Referenced by GetDate(), SensorRecord(), and SetDate().
m_solarRadiation
float SensorRecord::m_solarRadiation private
Definition at line 30 of file SensorRecord.h.
Referenced by GetSolarRadiation(), SensorRecord(), and SetSolarRadiation().
m_time
Time SensorRecord::m_time private
Definition at line 27 of file SensorRecord.h.
m_windSpeed
float SensorRecord::m_windSpeed private
Definition at line 28 of file SensorRecord.h.
Referenced by GetWindSpeed(), SensorRecord(), and SetWindSpeed().
The documentation for this class was generated from the following files:
SensorRecord.h
SensorRecord.cpp