ICT283 Assignment 1: MeasurementCalc Class Reference
MeasurementCalc Class Reference
Provides static methods for calculating statistical measurements on sensor data.
#include <MeasurementCalc.h>
Static Public Member Functions
static float CalculateMean (float sum, unsigned numCount)
Calculate the mean value.
static float CalculateStdDevWindSpeed (const Vector< SensorRecord > &sensorDataVector, float mean, unsigned numCount)
Calculate the standard deviation for wind speed.
static float CalculateStdDevAirTemp (const Vector< float > &tempArray, float mean)
Calculate the standard deviation for air temperature.
Detailed Description
Provides static methods for calculating statistical measurements on sensor data.
The class includes methods for calculating mean and standard deviation for wind speed and air temperature.
Author
Josie Lim
Version
1.0
Date
29/02/2024
Definition at line 23 of file MeasurementCalc.h.
Member Function Documentation
CalculateMean()
float MeasurementCalc::CalculateMean (float sum, unsigned numCount) static
Calculate the mean value.
Parameters
sum The sum of values.
numCount The number of values.
Returns
The calculated mean.
Definition at line 3 of file MeasurementCalc.cpp.
 {
     return sum / numCount;
 }
Referenced by MenuProcessor::MenuOptionFour(), MenuProcessor::MenuOptionOne(), and MenuProcessor::MenuOptionTwo().
CalculateStdDevAirTemp()
float MeasurementCalc::CalculateStdDevAirTemp (const Vector< float > & tempArray, float mean) static
Calculate the standard deviation for air temperature.
Parameters
tempArray The vector containing air temperature values.
mean The mean air temperature.
Returns
The calculated standard deviation for air temperature.
Definition at line 19 of file MeasurementCalc.cpp.
 {
     unsigned count = tempArray.GetSize();
     if (count <= 1)
     {
         return 0.0;
     }
     float sumSquaredDifferences = 0.0;
     for (unsigned i = 0; i < count; ++i)
     {
         float airTemp = tempArray[i];
         sumSquaredDifferences += pow(airTemp - mean, 2);
     }
     float stdDev = sqrt(sumSquaredDifferences / (count - 1));
     return stdDev;
 }
CalculateStdDevWindSpeed()
float MeasurementCalc::CalculateStdDevWindSpeed (const Vector< SensorRecord > & sensorDataVector, float mean, unsigned numCount) static
Calculate the standard deviation for wind speed.
Parameters
sensorDataVector The vector containing SensorRecord objects.
mean The mean wind speed.
numCount The number of values.
Returns
The calculated standard deviation for wind speed.
Definition at line 8 of file MeasurementCalc.cpp.
 {
     float sum = 0.0;
     for (unsigned i = 0; i < sensorDataVector.GetSize(); i++) {
         sum += pow(sensorDataVector[i].GetWindSpeed() - mean, 2);
     }
     return sqrt(sum / (numCount - 1));
 }
Referenced by MenuProcessor::MenuOptionFour(), and MenuProcessor::MenuOptionOne().
The documentation for this class was generated from the following files:
MeasurementCalc.h
MeasurementCalc.cpp