ICT283 Assignment 1: Time Class Reference
Time Class Reference
Represents a time with hours and minutes.
#include <Time.h>
Public Member Functions
Time ()
Default constructor for Time class.
Time (const string &hours, const string &minutes)
Parameterized constructor for Time class.
string GetHours () const
Retrieve the hours component of the time.
string GetMinutes () const
Retrieve the minutes component of the time.
void SetHours (const string &hours)
Set the hours component of the time.
void SetMinutes (const string &minutes)
Set the minutes component of the time.
Private Attributes
string m_hours
string m_minutes
Detailed Description
Represents a time with hours and minutes.
The class provides methods to get and set the hours and minutes.
Author
Josie Lim
Version
1.0
Date
27/02/24
Version
2.0
Date
29/02/24
Definition at line 34 of file Time.h.
Constructor & Destructor Documentation
Time() [1/2]
Time::Time ()
Default constructor for Time class.
Definition at line 3 of file Time.cpp.
     : m_hours("0"), m_minutes("00")
 {}
References Time().
Referenced by Time().
Time() [2/2]
Time::Time (const string & hours, const string & minutes)
Parameterized constructor for Time class.
Parameters
hours The hours component of the time.
minutes The minutes component of the time.
Definition at line 7 of file Time.cpp.
     : m_hours(hours), m_minutes(minutes)
 {}
References Time().
Referenced by Time().
Member Function Documentation
GetHours()
string Time::GetHours () const
Retrieve the hours component of the time.
Returns
The hours.
Definition at line 11 of file Time.cpp.
 {
     return m_hours;
 }
GetMinutes()
string Time::GetMinutes () const
Retrieve the minutes component of the time.
Returns
The minutes.
Definition at line 16 of file Time.cpp.
 {
     return m_minutes;
 }
SetHours()
void Time::SetHours (const string & hours)
Set the hours component of the time.
Parameters
hours The hours to be set.
Definition at line 21 of file Time.cpp.
 {
     m_hours = hours;
 }
SetMinutes()
void Time::SetMinutes (const string & minutes)
Set the minutes component of the time.
Parameters
minutes The minutes to be set.
Definition at line 26 of file Time.cpp.
 {
     m_minutes = minutes;
 }
Member Data Documentation
m_hours
string Time::m_hours private
Definition at line 37 of file Time.h.
m_minutes
string Time::m_minutes private
Definition at line 38 of file Time.h.
The documentation for this class was generated from the following files:
Time.h
Time.cpp