ICT283 Assignment 1: Date Class Reference
Date Class Reference
Represents a date with day, month, and year.
#include <Date.h>
Public Member Functions
Date ()
Default constructor for Date class.
Date (unsigned dayOfMonth, unsigned month, unsigned year)
Parameterized constructor for Date class.
unsigned GetDayOfMonth () const
Retrieve day of the month.
unsigned GetMonth () const
Retrieve month.
unsigned GetYear () const
Retrieve year.
void SetDayOfMonth (unsigned dayOfMonth)
Modify the day of the month.
void SetMonth (unsigned month)
Modify the month.
void SetYear (unsigned year)
Modify the year.
Private Attributes
unsigned m_dayOfMonth
unsigned m_month
unsigned m_year
Detailed Description
Represents a date with day, month, and year.
The class provides methods to get and set the day, month, and year.
Author
Josie Lim
Version
1.0
Date
21/02/24
Version
2.0
Date
29/02/24
Updated doxygen comments.
Definition at line 29 of file Date.h.
Constructor & Destructor Documentation
Date() [1/2]
Date::Date ()
Default constructor for Date class.
Definition at line 5 of file Date.cpp.
     : m_dayOfMonth(0), m_month(0), m_year(0)
 {}
References m_dayOfMonth, m_month, and m_year.
Date() [2/2]
Date::Date (unsigned dayOfMonth, unsigned month, unsigned year)
Parameterized constructor for Date class.
Definition at line 9 of file Date.cpp.
     : m_dayOfMonth(dayOfMonth), m_month(month), m_year(year)
 {}
References m_dayOfMonth, m_month, and m_year.
Referenced by Test2CheckParameterizedConstructor(), Test2CheckSetters(), Test3CheckDayOfMonthGetter(), Test4CheckMonthGetter(), and Test5CheckYearGetter().
Member Function Documentation
GetDayOfMonth()
unsigned Date::GetDayOfMonth () const
Retrieve day of the month.
Returns
The day of the month.
Definition at line 13 of file Date.cpp.
 {
     return m_dayOfMonth;
 }
References m_dayOfMonth.
Referenced by Test1CheckDefaultConstructor(), Test2CheckParameterizedConstructor(), Test3CheckDayOfMonthGetter(), and Test6CheckDayOfMonthSetter().
GetMonth()
unsigned Date::GetMonth () const
Retrieve month.
Returns
The month.
Definition at line 18 of file Date.cpp.
 {
     return m_month;
 }
References m_month.
Referenced by Test1CheckDefaultConstructor(), Test2CheckParameterizedConstructor(), Test2CheckSetters(), Test4CheckMonthGetter(), and Test7CheckMonthSetter().
GetYear()
unsigned Date::GetYear () const
Retrieve year.
Returns
The year.
Definition at line 23 of file Date.cpp.
 {
     return m_year;
 }
References m_year.
Referenced by Test1CheckDefaultConstructor(), Test2CheckParameterizedConstructor(), Test5CheckYearGetter(), and Test8CheckYearSetter().
SetDayOfMonth()
void Date::SetDayOfMonth (unsigned dayOfMonth)
Modify the day of the month.
Parameters
dayOfMonth The day of the month to be modified.
Definition at line 28 of file Date.cpp.
 {
     m_dayOfMonth = dayOfMonth;
 }
References m_dayOfMonth.
Referenced by Test6CheckDayOfMonthSetter().
SetMonth()
void Date::SetMonth (unsigned month)
Modify the month.
Parameters
month The month to be modified.
Definition at line 33 of file Date.cpp.
 {
     m_month = month;
 }
References m_month.
Referenced by Test7CheckMonthSetter().
SetYear()
void Date::SetYear (unsigned year)
Modify the year.
Parameters
year The year to be modified.
Definition at line 38 of file Date.cpp.
 {
     m_year = year;
 }
References m_year.
Referenced by Test8CheckYearSetter().
Member Data Documentation
m_dayOfMonth
unsigned Date::m_dayOfMonth private
Definition at line 32 of file Date.h.
Referenced by Date(), GetDayOfMonth(), and SetDayOfMonth().
m_month
unsigned Date::m_month private
Definition at line 33 of file Date.h.
Referenced by Date(), GetMonth(), and SetMonth().
m_year
unsigned Date::m_year private
Definition at line 34 of file Date.h.
Referenced by Date(), GetYear(), and SetYear().
The documentation for this class was generated from the following files:
Date.h
Date.cpp